### ISSUE TITLE
Updating via loan.FieldId["FR0108#1"].Value appends new records to the loan.Applications[0].Residences collection instead of updating the existing residence

### ISSUE THREAD

**Issue by AndrewAguayo** [EncompassRest/EncompassRest#286] opened 2019-09-10 15:59 UTC
When we attempt to update using the FR0108#1 fieldId's, such as loan.FieldId["FR0108#1"].Value = 90210, instead of updating current borrower residence in the 1st application, EncompassRest is appending new residences to the loan.Applications[x].Residences collection.   Is there a way to update the current and previous residence using the FieldId update?

**Comment by TylerBrinkley** [comment] 2019-09-19 16:46
I was unable to reproduce this. Do you have any code you could share?

**Comment by AndrewAguayo** [comment] 2019-09-20 14:18
Hi Tyler,  

Thank you in advance for looking at this  below is a unit test we created and the console output from it.  Hopefully this helps.

Unit test:
            var loanNumber = "360031885";
            var fieldId = "FR0108#1";
            var updateValue = "84124";

            //short cut so we can test different loan numbers
            var loanId = TestSettings.GetLoanId(loanNumber);

            var startingResidenceCount = 0;
            var startingValue = string.Empty;
            var postResidenceCount = 0;
            var postValue = string.Empty;

            try
            {
                using (var client = TestSettings.GetEncompassClient())
                {

                    //get loan before update, 
                    var loan = client.Loans.GetLoanAsync(loanId).GetAwaiter().GetResult();

                    var lmsgobj = new { LoanNumber = loanNumber, LoanId = loanId };
                    Console.WriteLine($"Testing Loan\n\t{JsonConvert.SerializeObject(lmsgobj)}");


                    //starting value
                    startingValue = loan.Fields[fieldId]?.Value?.ToString() ?? string.Empty;

                    var msgobj = new { StartingValue = startingValue, UpdateValue = updateValue };
                    string msg = $"Value to change\n\t{JsonConvert.SerializeObject(msgobj)}";
                    Console.WriteLine(msg);
                    Assert.AreNotEqual(startingValue, updateValue, $"Cannot test values are the same {msg}");

                    //residence count before update
                    startingResidenceCount = loan.Applications[0].Residences.Count;
                    
                    //create loan update object
                    var loanUpdate = new Loan(client, loanId);
                    loanUpdate.Fields[fieldId].Value = updateValue;
                    var loanUpdateString = loanUpdate.ToString();
                    Console.WriteLine($"Update object\n\t{loanUpdate}\n");

                    //perform update
                    client.Loans.UpdateLoanAsync(loanUpdate).GetAwaiter().GetResult();

                    //get updated loan
                    var loanPost = client.Loans.GetLoanAsync(loanId).GetAwaiter().GetResult();

                    //post residence count
                    postResidenceCount = loanPost.Applications[0].Residences.Count;

                    //post value
                    postValue = loan.Fields[fieldId]?.Value?.ToString() ?? string.Empty;


                    var resObj = new
                    {
                        StartingResidenceCount = startingResidenceCount,
                        PostResidenceCount = postResidenceCount,
                        StartingValue = startingValue,
                        PostValue = postValue
                    };
                    Console.WriteLine($"Result object\n\t{JsonConvert.SerializeObject(resObj)}\n");

                    Assert.AreEqual(startingResidenceCount,postResidenceCount,$"Residence Count Mismatch");
                    Assert.AreEqual(updateValue, postValue, "Value not updated");
                }
            }
            catch
            {
                throw;
            }


Output from the Console.Writelines:

Testing Loan
	{"LoanNumber":"360031885","LoanId":"386b1240-3b19-475c-9a44-92c831a95168"}
Value to change
	{"StartingValue":"84123","UpdateValue":"84124"}
Update object
	{"applications":[{"applicationIndex":0,"residences":[{"addressPostalCode":"84124","applicantType":"Borrower","mailingAddressIndicator":false,"residencyType":"Current"}]}],"encompassId":"386b1240-3b19-475c-9a44-92c831a95168"}

Result object
	{"StartingResidenceCount":16,"PostResidenceCount":17,"StartingValue":"84123","PostValue":"84123"}


Failure Message:
Assert.AreEqual failed. Expected:<16>. Actual:<17>. Residence Count Mismatch

**Comment by AndrewAguayo** [comment] 2019-09-20 14:29
A question is, it the Result object the JSON that is posted to encompass?  I'm thinking that without the id property for the residence, Encompass is creating a new Residence instead of updating an existing one.  I'm seeing something similar with updates to other fields contained in collections under the applications objects.     Here's the output of the residence entity from Encompass from postman:
{
    "encompassId": "386b1240-3b19-475c-9a44-92c831a95168",
    "applications": [
        {
            "id": "_borrower1",
            "residences": [
                {
                    "id": "Residence/0",
                    "addressCity": "Taylorsville",
                    "addressPostalCode": "84123",
                    "addressState": "UT",
                    "addressStreetLine1": "4581 Sunstone Road #108",
                    "altId": "_1065738416",
                    "applicantType": "Borrower",
                    "durationTermMonths": 8,
                    "durationTermYears": 0,
                    "residencyBasisType": "Own",
                    "residencyType": "Current",
                    "titleFax": "801-323-5751",
                    "titlePhone": "801-966-6630"
                },
                {
                    "id": "Residence/1",
                    "addressCity": "Taylorsville",
                    "addressPostalCode": "84123",
                    "addressState": "UT",
                    "addressStreetLine1": "4581 Sunstone Road #1099",
                    "altId": "_1957651805",
                    "applicantType": "Borrower",
                    "durationTermMonths": 2,
                    "durationTermYears": 4,
                    "residencyBasisType": "Rent",
                    "residencyType": "Prior",
                    "titleFax": "801-323-5751",
                    "titlePhone": "801-966-6630"
                },
                {
                    "id": "Residence/2",
                    "addressCity": "Taylorsville",
                    "addressPostalCode": "84123",
                    "addressStreetLine1": "4581 Sunstone Road #107",
                    "applicantType": "Borrower",
                    "residencyType": "Current"
                },
                {
                    "id": "Residence/3",
                    "addressCity": "Taylorsville",
                    "addressPostalCode": "84123",
                    "addressStreetLine1": "4581 Sunstone Road #107",
                    "applicantType": "Borrower",
                    "residencyType": "Current"
                },
                {
                    "id": "Residence/4",
                    "addressCity": "Taylorsville",
                    "addressPostalCode": "84123",
                    "addressStreetLine1": "4581 Sunstone Road #107",
                    "applicantType": "Borrower",
                    "residencyType": "Current"
                },
                {
                    "id": "Residence/5",
                    "addressCity": "Taylorsville",
                    "addressPostalCode": "84123",
                    "addressStreetLine1": "4581 Sunstone Road #107",
                    "applicantType": "Borrower",
                    "residencyType": "Current"
                },
                {
                    "id": "Residence/6",
                    "addressCity": "Taylorsville",
                    "addressPostalCode": "84123",
                    "addressStreetLine1": "4581 Sunstone Road 107",
                    "applicantType": "Borrower",
                    "residencyType": "Current"
                },
                {
                    "id": "Residence/7",
                    "addressCity": "Taylorsville",
                    "addressPostalCode": "84123",
                    "addressStreetLine1": "4581 Sunstone Road zzz",
                    "applicantType": "Borrower",
                    "residencyType": "Current"
                },
                {
                    "id": "Residence/8",
                    "addressCity": "Taylorsville",
                    "addressPostalCode": "84123",
                    "addressStreetLine1": "4581 Sunstone Road zzz",
                    "applicantType": "Borrower",
                    "residencyType": "Current"
                },
                {
                    "id": "Residence/9",
                    "addressStreetLine1": "4581 Sunstone Road",
                    "applicantType": "Borrower",
                    "residencyType": "Current"
                },
                {
                    "id": "Residence/10",
                    "addressStreetLine1": "4581 Sunstone Road",
                    "applicantType": "Borrower",
                    "residencyType": "Current"
                },
                {
                    "id": "Residence/11",
                    "addressCity": "Taylorsville",
                    "addressPostalCode": "84123",
                    "addressStreetLine1": "4581 Sunstone Road #107",
                    "applicantType": "Borrower",
                    "residencyType": "Current"
                },
                {
                    "id": "Residence/12",
                    "addressCity": "Taylorsville",
                    "addressPostalCode": "84123",
                    "addressStreetLine1": "4581 Sunstone Road #107",
                    "applicantType": "Borrower",
                    "residencyType": "Current"
                },
                {
                    "id": "Residence/13",
                    "addressCity": "Taylorsville",
                    "addressPostalCode": "84123",
                    "addressStreetLine1": "4581 Sunstone Road #107",
                    "applicantType": "Borrower",
                    "residencyType": "Current"
                },
                {
                    "id": "Residence/14",
                    "addressPostalCode": "84124",
                    "applicantType": "Borrower",
                    "residencyType": "Current"
                },
                {
                    "id": "Residence/15",
                    "addressPostalCode": "84124",
                    "applicantType": "Borrower",
                    "residencyType": "Current"
                },
                {
                    "id": "Residence/16",
                    "addressCity": "Taylorsville",
                    "addressPostalCode": "84123",
                    "addressState": "UT",
                    "addressStreetLine1": "4581 Sunstone Road #108",
                    "applicantType": "Borrower",
                    "mailingAddressIndicator": true
                }
            ]
        }
    ],
    "currentApplicationIndex": 0,
    "systemIdGuid": "5242edef-934c-44b6-b5fa-dc4b0fe08203"
}

**Comment by TylerBrinkley** [comment] 2019-09-20 16:16
I was able to reproduce this issue but no matter what I'm not able to update these fields without the residence object's id's being required. I believe this is an Ellie Mae issue. I've created an Ellie Mae forum post to let them know at https://forum.elliemae.com/index.php?/topic/8866-unable-to-update-residence-fields-without-id/.

As a workaround if you get the loan first and make updates to that loan object they will update the correct residence entity as the id will be included in the update request.

**Comment by yornstei** [comment] 2019-09-20 18:29
We've noticed this issue a while back and resulted to making the updates with the object id's as @TylerBrinkley mentioned (we get the loan first anyway); definitely an Ellie Mae issue though I don't think they're coming out with a better API for collections till next year.

**Comment by AndrewAguayo** [comment] 2019-09-20 21:38
Thanks @TylerBrinkley  for looking into this and posting to the Ellie Mae forum.  We appreciate what you're doing in Encompassrest.

**Closed** 2019-10-25 17:24 UTC
Labels: Ellie Mae Issue
